#!/usr/bin/python

import os
import sys

ascii_art_letters = """
-- a

 ██████
░░░░░███
 ███████
███░░███
░████████
░░░░░░░░

-- b

████
░███
░███
░███████
░███░░███
░███░░███
░░██████
 ░░░░░░

-- c

  ██████
 ███░░███
░███ ░░░
░███  ███
░░██████
 ░░░░░░

-- d
     ████
    ░░███
     ░███
  ███████
 ███░░███
░███░░███
░░██████
 ░░░░░░

-- e

  ██████
 ███░░███
░███████
░███░░░
░░███████
 ░░░░░░░

-- f

  ███████
 ░███░░███
 ░███ ░░░
 ██████
░░███░
 ░███
 █████
░░░░░

-- g

  ██████
 ███░░███
░░██████
░███░░░
░███████
░███░░███
░░██████
 ░░░░░░░

-- h

 ████
░░███
 ░███
 ░███
 ░███████
 ░███░░███
 ████░░███
░░░░  ░░░

-- i

  ███
 ░░░
  ███
 ░███
 ░███
 █████
░░░░░

-- j

      ███
     ░░░
     ████
    ░░███
     ░███
 ███░░███
░░█████░
 ░░░░░

-- k

 ████
░░███   ███
 ░███  ███
 ░███ ███
 ░██████
 ░███░░███
 █████░░████
░░░░░  ░░░░

-- l

 ████
░░███
 ░███
 ░███
 ░███
 ░███
 █████
░░░░░

-- m

 ██████████████
░░███░░███░░███
 ░███ ░███ ░███
 ░███ ░███ ░███
 █████░███ █████
░░░░░ ░░░ ░░░░░

-- n

 █████████
░░███░░███
 ░███ ░███
 ░███ ░███
 █████░████
░░░░░ ░░░░

-- o

  ██████
 ███░░███
░███ ░███
░███ ░███
░░██████
 ░░░░░░

-- p

 ████████
░░███░░███
 ░███ ░███
 ░███████
 ░███░░░
 ░███
 █████
░░░░░

-- q

  ██████
░███░░███
░███ ░███
░░███████
 ░░░░░███
     ░███
     ████
    ░░░░

-- r

 ████████
 ░░███░░███
  ░███ ░░░
  ░███
  █████
 ░░░░░

-- s

  █████
░███░░
 ░████
 ░░░███
 █████
░░░░░

-- t

  ███
 ░███
 ██████
░░███░
 ░███
 ░███  █
 ░░████
  ░░░░

-- u

█████ ████
░███ ░███
░███ ░███
░███ ░███
░████████
░░░░░░░░

-- v

 ████   ████
░░███   ███
 ░░███ ███
  ░░█████
   ░░███
    ░░░

-- w

 ████    ██    ████
░░███   ████   ███
 ░░███ ██████ ███
  ░░█████░░█████
   ░░███  ░░███
    ░░░    ░░░

-- x

 ████   ████
░░░███ ███░
  ░░█████
   ███ ███
 ████ ░░████
░░░░   ░░░░

-- y

 ███    ███
░░███  ███
 ░░██████
  ░░░███
 █  ███
░ ████
 ░░░░

-- z

 ███████
░░░░███
   ███
  ███
 ███████
░░░░░░░

-- .

 ███
░░░

-- -

 █████
░░░░░



-- _

 █████
░░░░░
"""[1:]

def parse_characters(letters):
    characters = dict()
    current_char = None

    for line in letters.split("\n"):
        if line[:2] == "--":
            current_char = line[3:].strip()

            characters[current_char] = list()
        else:
            characters[current_char].append(line[:-1])


    for char in characters:
        characters[char] = characters[char][1:-1]
        lines = characters[char]

        length = max([len(line) for line in lines])

        for i, line in enumerate(lines):
            lines[i] += " " * (length - len(line))

    return characters


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage:")
        print("ascii2art word ...;")
        print("")
        print("Each word's art is printed on a new line")
        exit(1)

    characters = parse_characters(ascii_art_letters)

    conv_text = []
    for arg in sys.argv[1:]:
        chars = [characters[char] for char in arg]
        num_lines = max([len(lines) for lines in chars])

        for i, lines in enumerate(chars):
            chars[i] = [" " * len(lines[0])] * (num_lines - len(lines)) + lines

        lines = [""] * num_lines
        for i in range(num_lines):
            for j in range(len(chars)):
                lines[i] += chars[j][i] + " "

        conv_text.append("\n".join(lines))

    print("\n\n".join(conv_text))
