#! /usr/bin/bash

ln -s $HOME/.extra/Dropbox $HOME/dropbox

git clone https://github.com/fat-fighter/iitk-courses.git $HOME/iitk
rm -rf $HOME/dropbox/iitk
ln -s $HOME/iitk/sem7 $HOME/dropbox/iitk

ln -s $HOME/utilities/dotfiles $HOME/dotfiles

mkdir -p $HOME/downloads
rm -f $HOME/Downloads
