#!/usr/bin/bash

software=(
	w3m
	exa
	feh
	wget
	xorg
	term
	file
	unzip
	atool
	screen
	evince
	poppler
	openssh
	nautilus
	xorg-init
	xdg-utils
	highlight
	git:light
	mediainfo
	xf86-video
	pavucontrol
	xorg-server
	git:dropbox
	git:lazygit
	lxappearance
	pacman-utils
	arc-gtk-theme
	gnome-screenshot
	git:google-chrome
	xf86-input-libinput
	git:urxvt-unicode-pixbuf
)

function pg {
	git clone https://aur.archlinux.org/$1.git
	cd $1
	makepkg -Acs --noconfirm
	if ls $1*.tar.xz 1> /dev/null 2>&1; then
		sudo pacman -U --noconfirm $1*.tar.xz
		cd ../
		rm -rf $1
	else
		echo "There was some error in downloading the package: $1"
		cd ../
	fi
}

for sw in ${software[@]}; do
	if [[ `echo $sw | cut -d':' -f1` == "git" ]]; then
		pg `echo $sw | cut -d':' -f2`
	else
		sudo pacman -S --noconfirm $sw
	fi
done

#  Custom Commands

## Dropbox
sudo systemctl enable dropbox@`whoami`

## Chrome
xdg-mime default ${desktop_file} x-scheme-handler/http
xdg-mime default ${desktop_file} x-scheme-handler/https

## Xorg
cat > ~/.xinitrc << EOT
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
exec i3
EOT
