#!/usr/bin/bash

software=(
	w3m
	exa
	feh
	tor
	wget
	xorg
	term
	file
	bluez
	light
	unzip
	atool
	screen
	evince
	poppler
	openssh
	#nautilus
	xorg-init
	xdg-utils
	git:light
	#mediainfo
	#highlight
	xf86-video
	bluez-utils
	pavucontrol
	xorg-server
	git:dropbox
	git:lazygit
	lxappearance
	pacman-utils
	git:siji-git
	arc-gtk-theme
	gnome-screenshot
	git:libsynaptics
	git:google-chrome
	git:skypeforlinux
	xf86-input-libinput
	git:urxvt-unicode-pixbuf
)

function pg {
	git clone https://aur.archlinux.org/$1.git
	cd $1
	makepkg -Acs --noconfirm
	if ls $1*.tar.xz 1> /dev/null 2>&1; then
		sudo pacman -U --noconfirm $1*.tar.xz
		cd ../
		rm -rf $1
	else
		echo "There was some error in downloading the package: $1"
		cd ../
	fi
}

for sw in ${software[@]}; do
	if [[ `echo $sw | cut -d':' -f1` == "git" ]]; then
		pg `echo $sw | cut -d':' -f2`
	else
		sudo pacman -S --noconfirm $sw
	fi
done

#  Custom Commands

## Dropbox
sudo systemctl enable dropbox@`whoami`

## Tor
sudo systemctl enable tor.service

## Browser
xdg-settings set default-web-browser qutebrowser.desktop

## Xorg
cat > ~/.xinitrc << EOT
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
exec i3
EOT
