#! /usr/bin/bash

# Installing pulsaudio
sudo pacman -S --noconfirm pulseaudio

# Installing asoundconf
git clone https://aur.archlinux.org/asoundconf.git
cd asoundconf
makepkg -Acs --noconfirm
sudo pacman -U --noconfirm asoundconf-*.tar.xz
cd ..
rm -rf asoundconf

# Setting default card to PCH
rm -rf ~/.asoundrc
asoundconf set-default-card PCH

echo "defaults.ctl.card PCH" >> ~/.asoundrc
echo "defaults.pcm.card PCH" >> ~/.asoundrc

exit 0
# Unmute and reset volumes for all sinks
sinks=( `pactl list sinks | grep '^Sink #' | sed 's/Sink #//g'` )
for sink in $sinks; do
	pactl set-sink-mute $sink 0
	pactl set-sink-volume $sink 100% 100%
done

# Custom Sink Settings
pactl set-sink-volume 0 70% 120%				# Front Left speaker is faulty

# Kill all instances of pulseaudio
# All bluetooth headsets will get disconnected
killall -q pulseaudio

# https://wiki.archlinux.org/index.php/PulseAudio/Examples#Automatically_switch_audio_to_HDMI
