install:
	sudo pacman -S --noconfirm python python-pip
	sudo pacman -S --noconfirm python2 python2-pip
	sudo rm /usr/bin/python
	sudo ln /usr/bin/python2 /usr/bin/python
	sudo rm /usr/bin/pip
	sudo ln /usr/bin/pip2 /usr/bin/pip
